services:
  myicon:
    image: heizicao/myicon:latest
    container_name: myicon
    ports:
      - 3000:3000
    volumes:
      - /mnt/user/appdata/myicon:/app/public/configData
    restart: unless-stopped